export const cuisineList = [
  "Jollof Rice",
  "Pounded Yam and Egusi Soup",
  "Suya",
  "Akara",
  "Moi Moi",
  "Fried Plantain (Dodo)",
  "Pepper Soup",
  "Fufu and Ogbono Soup",
  "Nigerian Fried Rice",
  "Amala and Ewedu Soup",
  "Banga Soup and Starch",
  "Oha Soup",
  "Edikang Ikong",
  "Afang Soup",
  "Bitterleaf Soup",
  "Abacha (African Salad)",
  "Efo Riro",
  "Okro Soup",
  "Egusi Soup",
  "Efo Elegusi",
  "Ewa Agoyin",
  "Puff Puff",
  "Chin Chin",
  "Zobo Drink",
  "Kunu Drink",
  "Soda",
  "Fruit Juice",
  "Carbonated Drink",
  "Yogurt Drink",
  "Suya Burger",
  "Shawarma",
  "Ice Cream",
  "Cake"
];
